# File name: docker-compose.yml
# Author: @nouryehia
# Description: Defines the containers to be used when running docker-compose. 

version: '3.7'

services:
    ag-backend:
        container_name: ag-backend
        command: python runner.py run -h 0.0.0.0
        volumes: [.:/usr/src/app]
        depends_on: [db]
        ports: [4200:5000]
        env_file: ./.env
        build:
            context: .
            dockerfile: Dockerfile
    db:
        container_name: db
        restart: on-failure
        ports: [5432:5432]
        env_file: ./.env
        build:
            context: ./data
            dockerfile: Dockerfile
